/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package university;

import com.mysql.cj.jdbc.Blob;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Name
 */
public class Student extends javax.swing.JFrame {

    ST_DB_Connection cdb = new ST_DB_Connection();

    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
        new ST_DB_Connection();
        Class_Load();
        Student_Load();
        setIconImage();
        setTitle("Student page");
    }

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));

    }

    int id;
    String uname;
    String usertype;

    public Student(int id, String username, String utype) {
        initComponents();
        new ST_DB_Connection();
        Class_Load();
        Student_Load();
        setIconImage();
        setTitle("Student page");
        this.uname = username;
        jLabel20.setText(uname);

        this.usertype = utype;
        jLabel21.setText(utype);

        if (utype.equals("Student")) {
            savebutton.setEnabled(false);
            editbutton.setEnabled(false);
            deletebutton.setEnabled(false);
            clearbutton.setEnabled(false);
        }

        if (utype.equals("Guest")) {
            savebutton.setEnabled(false);
            editbutton.setEnabled(false);
            deletebutton.setEnabled(false);
            clearbutton.setEnabled(false);

        } else {
            savebutton.setEnabled(true);
            editbutton.setEnabled(true);
            deletebutton.setEnabled(true);
            clearbutton.setEnabled(true);
        }

        this.id = id;

    }

    PreparedStatement pst;
    ResultSet rs;
    DefaultTableModel d;

    public void Class_Load() {

        try {
            pst = cdb.conn.prepareStatement("select Distinct dept_name from class");
            rs = pst.executeQuery();

            //txtclass.removeAllItems();
            while (rs.next()) {
                txtdept.addItem(rs.getString("dept_name"));
            }
            txtstid.setEnabled(false);
            txtimgpath.setEditable(false);
        } catch (SQLException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void Student_Load() {
        int c;
        try {
            pst = cdb.conn.prepareStatement("select * from student");
            rs = pst.executeQuery();

            ResultSetMetaData rsd = rs.getMetaData();
            c = rsd.getColumnCount();

            d = (DefaultTableModel) rSTableMetro1.getModel();
            d.setRowCount(0);
            while (rs.next()) {
                Vector<String> v2 = new Vector<>();
                for (int i = 1; i <= c; i++) {
                    v2.add(rs.getString("studentid"));
                    v2.add(rs.getString("studentname"));
                    v2.add(rs.getString("parentname"));
                    v2.add(rs.getString("dateofbirth"));
                    v2.add(rs.getString("gender"));
                    v2.add(rs.getString("studentmobileno"));
                    v2.add(rs.getString("studentaddress"));
                    v2.add(rs.getString("studentdepartment"));
                    v2.add(rs.getString("studentsession"));
                }
                d.addRow(v2);
            }
        } catch (SQLException ex) {
            System.err.println(ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtparentname = new javax.swing.JTextField();
        txtdateofbirth = new com.toedter.calendar.JDateChooser();
        txtgender = new javax.swing.JComboBox<>();
        txtmobile = new javax.swing.JTextField();
        txtaddress = new javax.swing.JTextField();
        txtdept = new javax.swing.JComboBox<>();
        txtsession = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        savebutton = new javax.swing.JButton();
        editbutton = new javax.swing.JButton();
        deletebutton = new javax.swing.JButton();
        clearbutton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtimgpath = new javax.swing.JTextField();
        imgupload = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtstid = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        searchButton = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtstname = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rSTableMetro1 = new javax.swing.JTable();
        uploadimg = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student Details:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 295, -1));

        txtparentname.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jPanel2.add(txtparentname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 225, 32));

        txtdateofbirth.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jPanel2.add(txtdateofbirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 225, 32));

        txtgender.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female" }));
        jPanel2.add(txtgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 225, 32));

        txtmobile.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtmobile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtmobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 225, 32));

        txtaddress.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jPanel2.add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 223, 32));

        txtdept.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtdept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        txtdept.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtdept, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 225, 32));

        txtsession.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "2019-20 (graduate)", "2021-22 (graduate)", "2022-23 (graduate)", "2024-25 (graduate)", "2024-25 (Masters)" }));
        txtsession.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(txtsession, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 660, 225, 32));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Address");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 220, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Parent Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 225, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date Of Birth");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 225, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Gender");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 225, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mobile No");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 220, -1));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Department");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 220, -1));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Session");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, 225, -1));

        savebutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        savebutton.setText("SAVE");
        savebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });
        jPanel2.add(savebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 790, 95, -1));

        editbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editbutton.setText("EDIT");
        editbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(editbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 790, 92, -1));

        deletebutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deletebutton.setText("DELETE");
        deletebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deletebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebuttonActionPerformed(evt);
            }
        });
        jPanel2.add(deletebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 830, 95, -1));

        clearbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearbutton.setText("CLEAR");
        clearbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(clearbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 830, 92, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/student.png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));
        jPanel2.add(txtimgpath, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 730, 130, 30));

        imgupload.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        imgupload.setText("Upload");
        imgupload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imguploadActionPerformed(evt);
            }
        });
        jPanel2.add(imgupload, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 730, 80, 30));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Image");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 710, 120, -1));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Student Name");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 225, -1));

        txtstid.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jPanel2.add(txtstid, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 225, 32));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/student.png"))); // NOI18N
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        searchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });
        jPanel2.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 30, 30));

        jLabel30.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Student Name");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 225, -1));

        jLabel29.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Image");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 710, 120, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 225, -1));

        txtstname.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jPanel2.add(txtstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 225, 32));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 870));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("USER NAME:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 6, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("USER TYPE:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 29, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("USER NAME");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 6, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("USER TYPE");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 29, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1750, 0, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("LOGOUT");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1690, 0, -1, 25));

        rSTableMetro1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name", "Parent Name", "Date of Birth", "gender", "Student Mobile Number", "Student Address", "Student Department Name", "Student Session"
            }
        ));
        rSTableMetro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSTableMetro1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(rSTableMetro1);
        if (rSTableMetro1.getColumnModel().getColumnCount() > 0) {
            rSTableMetro1.getColumnModel().getColumn(0).setPreferredWidth(100);
            rSTableMetro1.getColumnModel().getColumn(3).setPreferredWidth(80);
            rSTableMetro1.getColumnModel().getColumn(4).setMinWidth(100);
            rSTableMetro1.getColumnModel().getColumn(4).setPreferredWidth(100);
            rSTableMetro1.getColumnModel().getColumn(4).setMaxWidth(150);
            rSTableMetro1.getColumnModel().getColumn(6).setPreferredWidth(80);
            rSTableMetro1.getColumnModel().getColumn(7).setPreferredWidth(100);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 1420, 570));

        uploadimg.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(153, 153, 153)));
        jPanel1.add(uploadimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 200, 200));

        jMenu1.setText("Main Menu");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String sname = txtstid.getText();
            String parentname = txtparentname.getText();
            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String date = df.format(txtdateofbirth.getDate());
            String gender = txtgender.getSelectedItem().toString();
            String studentmobileno = txtmobile.getText();
            String studnetaddress = txtaddress.getText();
            String studentdept = txtdept.getSelectedItem().toString();
            String studentsession = txtsession.getSelectedItem().toString();
            String path = txtimgpath.getText();

            pst = cdb.conn.prepareStatement("insert into student(studentname,parentname,dateofbirth,gender,studentmobileno,studentaddress,studentdepartment,studentsession,studentphoto)values(?,?,?,?,?,?,?,?,?)");
            pst.setString(1, sname);
            pst.setString(2, parentname);
            pst.setString(3, date);
            pst.setString(4, gender);
            pst.setString(5, studentmobileno);
            pst.setString(6, studnetaddress);
            pst.setString(7, studentdept);
            pst.setString(8, studentsession);
            try {
                InputStream is = new FileInputStream(new File(path));
                pst.setBlob(9, is);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
            }

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Student details added successfully...");
            Student_Load();
        } catch (SQLException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        }
        clearstinfo();

    }//GEN-LAST:event_savebuttonActionPerformed

    private void editbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbuttonActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            d = (DefaultTableModel) rSTableMetro1.getModel();
            int selectIndex = rSTableMetro1.getSelectedRow();

            int id = Integer.parseInt(d.getValueAt(selectIndex, 0).toString());

            String sname = txtstid.getText();
            String parentname = txtparentname.getText();
            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String date = df.format(txtdateofbirth.getDate());
            String gender = txtgender.getSelectedItem().toString();
            String studentmobileno = txtmobile.getText();
            String studnetaddress = txtaddress.getText();
            String studentclass = txtdept.getSelectedItem().toString();
            String studentsection = txtsession.getSelectedItem().toString();
            String path = txtimgpath.getText();

            pst = cdb.conn.prepareStatement("update student set studentname=?,parentname=?,dateofbirth=?,gender=?,studentmobileno=?,studentaddress=?,studentdepartment=?,studentsession=?,studentphoto=? where studentid=?");

            pst.setString(1, sname);
            pst.setString(2, parentname);
            pst.setString(3, date);
            pst.setString(4, gender);
            pst.setString(5, studentmobileno);
            pst.setString(6, studnetaddress);
            pst.setString(7, studentclass);
            pst.setString(8, studentsection);
            try {
                InputStream is = new FileInputStream(new File(path));
                pst.setBlob(9, is);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
            }
            pst.setInt(10, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Student details edited successfully...");
            savebutton.setEnabled(true);

            clearstinfo();

            Student_Load();
        } catch (SQLException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_editbuttonActionPerformed

    private void deletebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebuttonActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            d = (DefaultTableModel) rSTableMetro1.getModel();
            int selectIndex = rSTableMetro1.getSelectedRow();

            int id = Integer.parseInt(d.getValueAt(selectIndex, 0).toString());

            pst = cdb.conn.prepareStatement("delete from student where studentid=?");
            pst.setInt(1, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "student details deleted successfully...");
            savebutton.setEnabled(true);

            clearstinfo();

            Student_Load();
            savebutton.setEnabled(true);

        } catch (SQLException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_deletebuttonActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        // TODO add your handling code here:
        clearstinfo();
        Student_Load();
        savebutton.setEnabled(true);

    }//GEN-LAST:event_clearbuttonActionPerformed

    public void clearstinfo() {
        txtstid.setText("");
        txtstname.setText("");
        txtparentname.setText("");
        txtdateofbirth.setDate(null);
        txtgender.setSelectedIndex(0);
        txtmobile.setText("");
        txtaddress.setText("");
        txtsession.setSelectedIndex(0);
        txtdept.setSelectedIndex(0);
        uploadimg.setIcon(null);
        txtimgpath.setText("");
    }
    private void rSTableMetro1AncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_rSTableMetro1AncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_rSTableMetro1AncestorRemoved

    private void rSTableMetro1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSTableMetro1MouseClicked
        // TODO add your handling code here:
        clearstinfo();
        try {
            // TODO add your handling code here:
            d = (DefaultTableModel) rSTableMetro1.getModel();
            int selectIndex = rSTableMetro1.getSelectedRow();

            txtstid.setText(d.getValueAt(selectIndex, 0).toString());

            savebutton.setEnabled(false);
        } catch (Exception ex) {
            Logger.getLogger(Exam.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rSTableMetro1MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        Main m = new Main(id, uname, usertype);
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void imguploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imguploadActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            String path = f.getAbsolutePath();

            BufferedImage bi = ImageIO.read(new File(path));
            Image img = bi.getScaledInstance(200, 200, Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(img);
            uploadimg.setIcon(icon);
            txtimgpath.setText(path);

        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_imguploadActionPerformed

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        
        search();
    }//GEN-LAST:event_searchButtonMouseClicked

    public void search() {
        String tid = txtstid.getText();

        try {
            pst = cdb.conn.prepareStatement("select * from student where studentid=?");
            pst.setString(1, tid);
            rs = pst.executeQuery();

            if (rs.next() == false) {
                JOptionPane.showMessageDialog(this, "Invalid ID");
                txtstid.setText("");
            } else {
                txtstname.setText(rs.getString("studentname"));
                txtparentname.setText(rs.getString("parentname"));
                txtdateofbirth.setDate(rs.getDate("dateofbirth"));
                txtgender.setSelectedItem(rs.getString("gender"));
                txtmobile.setText(rs.getString("studentmobileno"));
                txtaddress.setText(rs.getString("studentaddress"));
                txtdept.setSelectedItem(rs.getString("studentdepartment"));
                txtsession.setSelectedItem(rs.getString("studentsession"));

                Blob image = (Blob) rs.getBlob("studentphoto");
                String path = "C:\\Users\\User\\Downloads\\School-Management-System-using-Java-main\\src\\schoolmanagementsystem\\uploadimg\\img.jpg";
                byte[] bte = image.getBytes(1, (int) image.length());
                FileOutputStream ft = new FileOutputStream(path);
                ft.write(bte);
                BufferedImage bi = ImageIO.read(new File(path));
                Image img = bi.getScaledInstance(200, 200, Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(img);

                uploadimg.setIcon(icon);

                txtimgpath.setText(path);
                txtstid.setEditable(false);

            }
        } catch (SQLException ex) {
            Logger.getLogger(Mark.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Teacher.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearbutton;
    private javax.swing.JButton deletebutton;
    private javax.swing.JButton editbutton;
    private javax.swing.JButton imgupload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable rSTableMetro1;
    private javax.swing.JButton savebutton;
    private javax.swing.JLabel searchButton;
    private javax.swing.JTextField txtaddress;
    private com.toedter.calendar.JDateChooser txtdateofbirth;
    private javax.swing.JComboBox<String> txtdept;
    private javax.swing.JComboBox<String> txtgender;
    private javax.swing.JTextField txtimgpath;
    private javax.swing.JTextField txtmobile;
    private javax.swing.JTextField txtparentname;
    private javax.swing.JComboBox<String> txtsession;
    private javax.swing.JTextField txtstid;
    private javax.swing.JTextField txtstname;
    private javax.swing.JLabel uploadimg;
    // End of variables declaration//GEN-END:variables
}
